### ISSUE TITLE
Further work

### ISSUE THREAD

**Issue by MLlover** [luizgh/sigver_wiwd#4]
hey, what if we add a new user with different class. then do we need to train it again?

**Comment by luizgh** [comment]
If the objective is a signature verification system (the subject of the article), you don't need to re-train the network. The idea is to use the network as a feature extractor (i.e. transfer learning), and train a binary classifier for the new user.

**Comment by chunkypilu** [comment]
Sir,
I tried to read "signet.pkl" file in python 3.6  but I am getting error: 

code:
`from six.moves import cPickle
 `
`with open('signet.pkl', 'rb') as f:`
            `model_params = cPickle.load(f)`
 
error:

`Traceback (most recent call last):`
  `File "<ipython-input-39-0593160b4786>", line 3, in <module>`
    `model_params = cPickle.load(f)`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)`

I tried
 `with open('signet.pkl', 'rb').read().decode('utf8')`  but its not working.

**Comment by Vijay2611** [comment]
Objective is to check whether two signs match or not.
I have few doubts regarding training of binary classfier. please clear these doubts.
1. do I need to append features of real_X.mat and forg_X.mat to make a new feature vector. and if I append one feature vector(for one real signature) of real_X.mat to another feature vector(for another real signature of same user) of real_X.mat, then class is 1 otherwise it's 0.
2. do I need to train svm for all the users one by one?

**Comment by chunkypilu** [comment]
1. One signature gives one feature vector (feed sign. image to CNN and get feature vector from penultimate layer of CNN), now if this sign. is real sign. of user then class=1 otherwise class=0 (if this sign. is **forgery of same user** or **real of other user** or **forgery of other user**).

2. Yes (can be done in loop)
@luizgh, please correct me if I am wrong.

**Comment by luizgh** [comment]
@chunkypilu - your comments are correct. Note, however, that in our experiments we only trained the user classifiers using genuine signatures (i.e. use real signatures from other users as negative samples). You could train a classifier using forgeries, but this is a less realistic scenario (i.e. someone would need to create forgeries for all users in your training set). 

You could use, for instance:
User 2: 12 real signatures from this user as positive samples; 12 real signatures from each user in the development set (12 x 531 = 6372 signatures)  as negative samples. Train a binary classifier, possibly correcting for the skew (e.g., in scikit-learn user a class_skew of 1:531)

I hope this helps

**Comment by MLlover** [comment]
Thanks for the reply.

1. Can I change canvas size? will it have any effect on accuracy?

2. Feature vector in GPDS data sets has size equal to 2048. so can I use these features to train SVM?(size of phi(X) is 4096 in your paper for writer dependent classification.)

3. I'm thinking to subtract two feature vectors(GPDS data sets) of two signatures to create new feature vector(to be trained on svm). if both signatures are real signatures of same user then class=1, else class = 0. (eg. "feature1=[2,1,4]" , "feature2 = [4,1,3]" then new feature vector is "feature_new = absolute(feature1-feature2)=[2,0,1]" and assume class = 1. I construct data in this fashion and train these feature_new on svm.). Is this right approach?

Thanks in advance

**Comment by luizgh** [comment]
Hi, here are the answers for your questions:

1) You can change the canvas size, but not the size of the input to the network. It will probably affect the accuracy, but it is hard to tell how big the effect would be - you can try different canvas sizes and check the performance on a validation set.

2) In the journal paper (https://arxiv.org/pdf/1705.05787.pdf) we used a representation phi(X) of size 2048 - this is the version that was published in this repository.

3) That is a common approach to train a WI (writer-independent) classifier - it is called a "dissimilarity representation" (you can also see the term "dichotomy transformation" in the literature). This is called Writer-independent since it will be a single classifier for all users.

I hope this helps

**Comment by chunkypilu** [comment]
@MLlover 
Why do you think that creating new feature vector by subtracting two feature vectors will be a good idea?

**Comment by luizgh** [comment]
@chunkypilu this is a common transformation to enable training a single (global) classifier for all users. 

Instead of training one classifier per user, you train a classifier on the difference between a query signature and a reference signature. Here is an example of paper that uses this idea for signature verification: https://en.etsmtl.ca/ETS/media/ImagesETS/Labo/LIVIA/Publications/2013/Eskander_IET-Biometrics_2013.pdf

**Comment by MLlover** [comment]
Thanks Luizgh,

How did you handle skewness to train SVM. I'm using sklearn.should I use class_weight?

**Comment by luizgh** [comment]
Exactly. I calculated the skew on the training set (skew = n_positive/n_negative), and used class_weight={1: skew}

**Comment by MLlover** [comment]
thanks,
Please answer one more question.

To train binary classifier for each user, how did you do it? I'm doing it as follows.
pseudo code:

clf = svm()
for user in users:
    features =[[]]
    labels=[]      
    clf.fit(features,labels)
pickle.dump(clf)

or do I need to dump classfier for each user?

**Comment by chunkypilu** [comment]
@MLlover  I am doing like this:
https://gist.github.com/chunkypilu/60b52b0014a967d6cffc64d1cf0462fb

**Comment by MLlover** [comment]
Hi chunkypilu,
It's taking too much time to train the SVM. How much time does it take to train the svm?
and one more thing
How do you dump the classifier?

**Comment by chunkypilu** [comment]
I was just calculating FAR and FRR, so I thought no need to dump.

**Comment by chunkypilu** [comment]
@luizgh ,have you seen this paper: (https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7830802)
here they are extracting signature features using DCGAN, how does it helps?

**Comment by luizgh** [comment]
Hi @chunkypilu,

I have done some experiments with GANs a while ago, but I could not get good results on generating synthetic signatures - maybe because the dimensionality is too big for the number of examples we have (we need to generate large images, otherwise there is no details on the "pen strokes"). Also, note that for classification, GANs are usually used in a semi-supervised setting (e.g. where we don't have labels for most of the examples), which I couldn't find an application in signature verification (usually you would know which person wrote a signature).

About the paper you cited: I read that paper a while ago, and I found that it lacks many critical details (like the size of the images and the size of the feature vectors). I also found it strange that they did not include any single image of a generated signature - so we cannot know if the generator was actually generating something that looks like signatures, or only generating garbage.
